[registries]

  # once AuthN gets in we could do fine grained acl based
  # on users/groups
  #
  # deny|allow = [[users|groups...], [action...]]

  [registries."*"]
  deny = [["*"], ["*"]]
  allow = [["foo"], ["push", "pull"]]

  [registries."openshift.com"]
  allow = [["*"], ["*"]]

  #[registries."redhat.io"]
  #allow = ["search"]
  #deny = ["pull", "push"]
