[registries]

  # once AuthN gets in we could do fine grained acl based
  # on users/groups

  [registries."*"]
  deny = ["*"]

  [registries."openshift.com"]
  allow = ["*"]

  [registries."redhat.io"]
  allow = ["search"]
  deny = ["pull", "push"]
